### PR TITLE
Refs [TASK][27100] Init project, config CI

### PR DESCRIPTION
**Pull request by ducvv-0113**

### CODE REVIEW

**Comment by ducvv-0113** [comment]
ready

**Comment by manhnt-0960** [comment]
commented
link redmine đâu e, ảnh chạy CI nữa

**Comment by ducvv-0113** [comment]
https://edu-redmine.sun-asterisk.vn/issues/27100

**Comment by ducvv-0113** [comment]
Screenshot from 2020-08-13 13-10-17

**Comment by ducvv-0113** [comment]
ready

**Pull request merged**
